### ISSUE TITLE
[next branch] no logs when `verbose=False`

### ISSUE THREAD

**Issue by hadim** [MolSSI/QCFractal#728]
At https://github.com/MolSSI/QCFractal/blob/next/qcfractalcompute/qcfractalcompute/qcfractal_manager_cli.py#L712, the `INFO` logs are shown if I replace:

```python
    logger_map = {AdapterEnum.pool: "", AdapterEnum.dask: "dask_jobqueue.core", AdapterEnum.parsl: "parsl"}
    if settings.common.verbose:
        adapter_logger = logging.getLogger(logger_map[settings.common.adapter])
        adapter_logger.setLevel("DEBUG")
        logger.setLevel("DEBUG")
```

by 

```python
    logger_map = {AdapterEnum.pool: "", AdapterEnum.dask: "dask_jobqueue.core", AdapterEnum.parsl: "parsl"}
    adapter_logger = logging.getLogger(logger_map[settings.common.adapter])
    if settings.common.verbose:
        adapter_logger.setLevel("DEBUG")
        logger.setLevel("DEBUG")
    else:
        adapter_logger.setLevel("INFO")
        logger.setLevel("INFO")
```

**Comment by hadim** [comment]
@bennybp I still cannot see the logs when using `INFO` level with `qcfractal-compute-manager`.

It works if I specify the name of the logger in `compute_manager_cli.py`:

```python
    # Adjust the logging level to what was in the config
    logging.getLogger().setLevel(manager_config.loglevel)

    if manager_config.logfile:
        print("*" * 10)
        print(f"Logging to file {manager_config.logfile}, logging level {manager_config.loglevel}")
        print("*" * 10)
        log_handler = logging.FileHandler(manager_config.logfile)
        log_handler.setFormatter(formatter)
        logging.getLogger().handlers = [log_handler]
```

to 

```python
    # Adjust the logging level to what was in the config
    logging.getLogger("ComputeManager").setLevel(manager_config.loglevel)

    if manager_config.logfile:
        print("*" * 10)
        print(f"Logging to file {manager_config.logfile}, logging level {manager_config.loglevel}")
        print("*" * 10)
        log_handler = logging.FileHandler(manager_config.logfile)
        log_handler.setFormatter(formatter)
        logging.getLogger("ComputeManager").handlers = [log_handler]
```

**Comment by bennybp** [comment]
I will have to test, but I think I need to `.clear()` the handlers, then add the new handlers (rather than what I did). I think that is the more proper way to do that (since some logging code may still be pointing at the old handler list, I need to modify in-place)

**Comment by bennybp** [comment]
I'm having trouble reproducing with the new manager. It always seems to print whether or not I specify `--verbose`. Do you have an example config/env vars/command line?

**Comment by hadim** [comment]
I am not using `--verbose` simply `qcfractal-compute-manager --config config.yaml`

```yaml
# The base folder to use as the default for some options (logs, etc).
base_folder: /tmp/qcf_compute

# Name of this scheduler to present to the Fractal Server. Descriptive names help
# the server identify the manager resource and assists with debugging.
cluster: manager_demo_1

loglevel: INFO
logfile: null

# Time between heartbeats/update checks between this Manager and the Fractal Server.
update_frequency: 30

# Settings to connect to the Fractal Server.
server:
  fractal_uri: http://127.0.0.1:7777
  username: compute_user
  password: compute_password
  verify: false

# How and where to detect the QM softwares.
environments:
  use_manager_environment: true
  conda: []
  apptainer: []

executors:
  local:
    type: local

    # Common to all executors.
    queue_tags: ["demo"]
    worker_init: []
    scratch_directory: null
    bind_address: null
    cores_per_worker: 16
    memory_per_worker: 16 # GB
    extra_executor_options: {}

    # Specific options for the local executor.
    max_workers: 1
```
