### ISSUE TITLE
Worker getting removed

### ISSUE THREAD

**Issue by FNTwin** [MolSSI/QCFractal#850]
I'm running some SPC with the qcportal suite and I'm using the `SlurmExecutor` to scale up the number of computation on slurm. The issue is that not all the workers requested from the config gets allocated (could be that my cluster is at capacity) but after a while, the workers correctly allocated get `CANCELLED`. Looking at the interchange.log I can see the Managers have compatible Parsl version and Python version but at some point I get:

```
Interchange-Command _command_server [INFO] Received HOLD_WORKER 
MainThread expire_bad_managers [WARNING] Too many heartbeats missed for manager
``` 

The workers/managers get removed from the SLURM queue and new one get allocated.

Some addictional info, i'm using a qcfractal manager config with `update_frequency: 10`, while the server config has the `heartbeat_frequency:10` too. I tried to increase both the `update_frequency` and the `heartbeat_frequency` with no avail.

**Comment by bennybp** [comment]
Are you submitting the managers themselves as jobs, or running a manager on the head node which delegates out to the SLURM queue? If it's the former, there may be a misconfiguration somewhere.

The first error here (`Interchange-Command...` comes from Parsl error, which means that Parsl itself is having issues spinning up workers.

Either way, is there anything in the logs for the QCFractal instance? That will usually have a little bit more info, although I'm guessing it's just managers not reporting back.

**Comment by FNTwin** [comment]
Hi @bennybp , The configuration that I setup is Server on the Head Node + Manager on the Head Node that delegates out the SLURM queues with the workers. I'll restart the server with DEBUG mode for the logging as I didn't see any useful logs from the info. 

> The first error here (Interchange-Command... comes from Parsl error, which means that Parsl itself is having issues spinning up workers.

Yep, for some reason it spins up correctly the workers (slurm allocate the jobs) but they get put on hold because for some reason their idletime always surpass the max_idletime from parsl.

About the config, I used the same config on another slurm cluster and it was pretty much working correctly (I also suspect that I have some I/O latency or some other issues as the SPC seems rather slow, any advice on how can I benchmark the retrieval of the jobs and the queue?)

I posted the config that I'm currently using:

```yaml
cluster: slurm_manager        
loglevel: DEBUG 
logfile: qcfractal-manager.log
update_frequency: 180.0 # I updated this 

server:
  fractal_uri: xxxxx
  username: xxxxx
  password: xxxxx
  verify: False


executors:
  slurm_executor:
    type: slurm
    scratch_directory: ${HOME}/project/qcfractal
    walltime: "72:00:00"
    exclusive: false 
    partition: compute
    account: null
    workers_per_node: 20 
    max_nodes: 30
    cores_per_worker: 8         
    memory_per_worker: 8        
    queue_tags:                 
      - '*'
    environments:
      use_manager_environment: False
      conda:  
        - qcfractal-worker 
    worker_init: 
      - source worker-init.sh  # abs path for the init for the worker
``` 

with a pretty standard worker-init.sh: 
```shell
#!/bin/bash

source ~/.bashrc
conda init 

ulimit -s unlimited
mkdir -p "${HOME}/project/qcfractal"
cd "${HOME}/project/qcfractal"
source ${HOME}/conda/bin/activate qcfractal_manager
```  

I know that parsl would require full exclusivity of the node, could it be a big issue currently that I'm not enabling it?
